### ISSUE TITLE
cancel crashes app

### ISSUE THREAD

**Issue by olli3** [appcelerator-modules/ti.barcode#88]
Using example here verbatum , android pixel2 - android 10

https://github.com/appcelerator-modules/ti.barcode/blob/master/ios/example/app.js

when i try to cancel or press back the app crashes eventually bringing up the 'wait or kill app' prompt

**Comment by m1ga** [comment]
Any log? E.g. when you run it with `--log-level trace`?
I don't have a Android 10 phone so I can't really test/debug it

**Comment by olli3** [comment]
i see this in the console

[WARN]  ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@57a6f3d
[WARN]  TiUIScrollView: (main) [5399,5399] Scroll direction could not be determined based on the provided view properties. Default VERTICAL scroll direction being used. Use the 'scrollType' property to explicitly set the scrolling direction.
[WARN]  ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@e113a62
[WARN]  MediaPlayer: Use of stream types is deprecated for operations other than volume control
[WARN]  MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
[INFO]  CameraConfiguration: Supported preview sizes: 1920x1080 1600x1200 1440x1080 1200x1200 1280x960 1280x720 1024x768 800x600 720x480 640x480 640x360 480x360 480x320 352x288 320x240 176x144 160x120
[INFO]  CameraConfiguration: No suitable preview sizes, using default: Point(1920, 1080)
[INFO]  CameraConfiguration: Supported preview sizes: 1920x1080 1600x1200 1440x1080 1200x1200 1280x960 1280x720 1024x768 800x600 720x480 640x480 640x360 480x360 480x320 352x288 320x240 176x144 160x120
[INFO]  CameraConfiguration: No suitable preview sizes, using default: Point(1920, 1080)
[INFO]  CameraConfiguration: Requesting flash mode value from among: [off]
[INFO]  CameraConfiguration: Supported flash mode values: [off, auto, on, torch]
[INFO]  CameraConfiguration: Can set flash mode to: off
[INFO]  CameraConfiguration: Flash mode already set to off
[INFO]  CameraConfiguration: Requesting focus mode value from among: [auto]
[INFO]  CameraConfiguration: Supported focus mode values: [infinity, auto, macro, continuous-video, continuous-picture]
[INFO]  CameraConfiguration: Can set focus mode to: auto
[INFO]  CameraConfiguration: Focus mode already set to auto
[INFO]  Choreographer: Skipped 73 frames!  The application may be doing too much work on its main thread.
[INFO]  OpenGLRenderer: Davey! duration=1236ms; Flags=0, IntendedVsync=330189158554254, Vsync=330190375220872, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=330190390499201, AnimationStart=330190390520451, PerformTraversalsStart=330190390737639, DrawStart=330190390803784, SyncQueued=330190391533628, SyncStart=330190391547170, IssueDrawCommandsStart=330190391624982, SwapBuffers=330190392755607, FrameCompleted=330190395379514, DequeueBufferDuration=197000, QueueBufferDuration=402000,
[INFO]  OpenGLRenderer: Davey! duration=1293ms; Flags=1, IntendedVsync=330189158554254, Vsync=330190375220872, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=330190390499201, AnimationStart=330190390520451, PerformTraversalsStart=330190390737639, DrawStart=330190398282014, SyncQueued=330190400655817, SyncStart=330190400998890, IssueDrawCommandsStart=330190405721390, SwapBuffers=330190451399936, FrameCompleted=330190452868582, DequeueBufferDuration=5249000, QueueBufferDuration=233000,
[INFO]  APSAnalyticsRunnable: Analytics Started
[INFO]  APSAnalyticsRunnable: Analytics service flush complete
[INFO]  APSAnalyticsRunnable: Stopping Service
[WARN]  ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b127b91
[INFO]  I/ongb.stockandg: Waiting for a blocking GC ProfileSaver
[INFO]  I/ongb.stockandg: WaitForGcToComplete blocked ProfileSaver on HeapTrim for 8.315ms
[WARN]  W/ongb.stockandg: Thread attaching while runtime is shutting down: Binder:7396_4
[INFO]  AndroidRuntime: NOTE: attach of thread 'Binder:7396_4' failed

**Comment by m1ga** [comment]
the module still uses zxing 3.3.1from Oct 2017 that might cause some issues on Android 10. I think they've added some changes to the camera usage. But it's a bit hard to test. I'll check if I can update to the latest zxing version!

**Comment by olli3** [comment]
UPDATE

Now crashes on android 7
 trace log

[INFO]  W/SyubId=1, ss=0 0 : 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
[INFO]  Project built successfully in 1m 444ms

[ERROR] Zygote: v2
[ERROR] Zygote: accessInfo : 0
[WARN]  SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0010, [-1 -1 -1 -1 0 1]
[INFO]  SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.graftongb.stockandgo
[DEBUG] TimaKeyStoreProvider: TimaKeyStore is enabled: try add TimaSignature Service and generateKeyPair Service
[INFO]  TiApplication: (main) [0,0] checkpoint, app created.
[INFO]  TiApplication: (main) [129,129] Titanium 7.5.0 (2018/08/28 23:14 undefined)
[INFO]  MultiDex: VM with version 2.1.0 has multidex support
[INFO]  MultiDex: Installing application
[INFO]  MultiDex: VM has multidex support, MultiDex support library is disabled.
[DEBUG] APSAnalytics: APSAnalytics initialization started...
[TRACE] updating tiapp metadata with Appcelerator Platform...
[INFO]  TiApplication: (main) [2237,2366] Titanium Javascript runtime: v8
[INFO]  TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
[WARN]  art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
[WARN]  APSAnalytics: APSAnalytics is already initialized. Skipping...
[DEBUG] TextView: setTypeface with style : 0
[WARN]  art: Suspending all threads took: 9.536ms
[INFO]  art: Background partial concurrent mark sweep GC freed 440(53KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 6MB/11MB, paused 14.294ms total 66.502ms
[INFO]  TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = com.graftongb.stockandgo.StockandgoActivity@8333ad8
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: ThreadedRenderer.create() translucent=false
[DEBUG] InputTransport: Input channel constructed: fd=56
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: setView = DecorView@a04dbd6[StockandgoActivity] touchMode=true
[DEBUG] InputMethodManager: HSI from window - flag : 0 Pid : 4124
[INFO]  InputMethodManager: HSI ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :0
[WARN]  TiUIScrollView: (main) [218,218] Scroll direction could not be determined based on the provided view properties. Default VERTICAL scroll direction being used. Use the 'scrollType' property to explicitly set the scrolling direction.
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] Window: Checkpoint: postWindowCreated()
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: ThreadedRenderer.create() translucent=true
[DEBUG] InputTransport: Input channel constructed: fd=57
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: setView = DecorView@70bc359[TiActivity] touchMode=true
[DEBUG] InputMethodManager: HSI from window - flag : 0 Pid : 4124
[INFO]  InputMethodManager: HSI ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :0
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: dispatchAttachedToWindow
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][720,1280] result=0x27 surface={isValid=true -903028736} surfaceGenerationChanged=true
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: mHardwareRenderer.initialize() mSurface={isValid=true -903028736} hwInitialized=true
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: dispatchAttachedToWindow
[INFO]  OpenGLRenderer: Initialized EGL, version 1.4
[DEBUG] OpenGLRenderer: Swap behavior 1
[DEBUG] mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [720x1280]-format:1
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][720,1280] result=0x7 surface={isValid=true -903026688} surfaceGenerationChanged=true
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: mHardwareRenderer.initialize() mSurface={isValid=true -903026688} hwInitialized=true
[DEBUG] mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [720x1280]-format:1
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
[TRACE] Uploaded tiapp metadata with Appcelerator Platform!
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
[INFO]  APSAnalyticsRunnable: Analytics Started
[DEBUG] NetworkSecurityConfig: No Network Security Config specified, using platform default
[INFO]  I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO]  I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO]  APSAnalyticsRunnable: Analytics service flush complete
[INFO]  APSAnalyticsRunnable: Stopping Service
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: MSG_RESIZED: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: MSG_RESIZED: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: MSG_WINDOW_FOCUS_CHANGED 1
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -903026688}
[TRACE] InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@8c93a00 nm : com.graftongb.stockandgo ic=null
[INFO]  InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
[DEBUG] InputTransport: Input channel constructed: fd=77
[TRACE] InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@959e239 nm : com.graftongb.stockandgo ic=null
[INFO]  I/InputDispatcher( 4047): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: ViewPostImeInputStage processPointer 0
[WARN]  System: ClassLoader referenced unknown path: /system/framework/QPerformance.jar
[ERROR] BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
[TRACE] BoostFramework: BoostFramework() : mPerf = null
[INFO]  I/InputDispatcher( 4047): Delivering touch to : action: 0x1, toolType: 1
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: ViewPostImeInputStage processPointer 1
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: MSG_WINDOW_FOCUS_CHANGED 0
[DEBUG] InputMethodManager: HSI from window - flag : 0 Pid : 4124
[DEBUG] TextView: setTypeface with style : 0
[DEBUG] TextView: setTypeface with style : 0
[INFO]  art: Do partial code cache collection, code=28KB, data=29KB
[INFO]  art: After code cache collection, code=22KB, data=25KB
[INFO]  art: Increasing code cache capacity to 128KB
[INFO]  MediaPlayer: Need to enable context aware info
[TRACE] V/MediaPlayer-JNI: native_setup
[TRACE] MediaPlayer: constructor
[TRACE] MediaPlayer: setListener
[TRACE] V/MediaPlayer-JNI: setDataSourceFD: fd 76
[TRACE] MediaPlayer: setDataSource(76, 5194140, 6401)
[TRACE] V/MediaPlayer-JNI: setAudioStreamType: 3
[TRACE] MediaPlayer: MediaPlayer::setAudioStreamType
[TRACE] V/MediaPlayer-JNI: setLooping: 0
[TRACE] MediaPlayer: MediaPlayer::setLooping
[TRACE] V/MediaPlayer-JNI: setVolume: left 0.100000  right 0.100000
[TRACE] MediaPlayer: MediaPlayer::setVolume(0.100000, 0.100000)
[TRACE] MediaPlayer: setVideoSurfaceTexture
[TRACE] MediaPlayer: prepare
[TRACE] MediaPlayer: message received msg=200, ext1=10973, ext2=0
[WARN]  MediaPlayer: info/warning (10973, 0)
[TRACE] MediaPlayer: callback application
[TRACE] MediaPlayer: back from callback
[TRACE] MediaPlayer: message received msg=1, ext1=0, ext2=0
[TRACE] MediaPlayer: prepared
[TRACE] MediaPlayer: signal application thread
[TRACE] MediaPlayer: callback application
[TRACE] MediaPlayer: back from callback
[TRACE] MediaPlayer: prepare complete - status=0
[DEBUG] MediaPlayer: setSubtitleAnchor in MediaPlayer
[TRACE] MediaPlayer: invoke 68
[DEBUG] DecodeHintManager: Hints from the Intent: {}
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: ThreadedRenderer.create() translucent=false
[DEBUG] InputTransport: Input channel constructed: fd=81
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: setView = DecorView@d2a24bb[CaptureActivity] touchMode=true
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: mHardwareRenderer.destroy()#1
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: dispatchAttachedToWindow
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][720,1280] result=0x7 surface={isValid=true -903028736} surfaceGenerationChanged=true
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: mHardwareRenderer.initialize() mSurface={isValid=true -903028736} hwInitialized=true
[DEBUG] mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [720x1280]-format:1
[DEBUG] SurfaceView: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][720,1280] result=0x7 surface={Surface(name=null)/@0x5c4cdd8 isValid=true -899799040}
[DEBUG] D/com.google.zxing.client.android.camera.open.OpenCameraInterface: Opening camera #0
[DEBUG] CameraConfiguration: Display at: 0
[DEBUG] CameraConfiguration: Camera at: 90
[DEBUG] CameraConfiguration: Final display orientation: 90
[DEBUG] CameraConfiguration: Clockwise rotation from display to camera: 90
[DEBUG] CameraConfiguration: Screen resolution in current orientation: Point(720, 1280)
[INFO]  CameraConfiguration: Supported preview sizes: 1280x720 1056x704 960x720 880x720 720x720 720x480 640x480 352x288 320x240 176x144
[INFO]  CameraConfiguration: No suitable preview sizes, using default: Point(1280, 720)
[DEBUG] CameraConfiguration: Camera resolution: Point(1280, 720)
[INFO]  CameraConfiguration: Supported preview sizes: 1280x720 1056x704 960x720 880x720 720x720 720x480 640x480 352x288 320x240 176x144
[INFO]  CameraConfiguration: No suitable preview sizes, using default: Point(1280, 720)
[DEBUG] CameraConfiguration: Best available preview size: Point(1280, 720)
[DEBUG] CameraConfiguration: Preview size on screen: Point(720, 1280)
[DEBUG] CameraConfiguration: Initial camera parameters: 3dnr=false;Infinity=Infinity;antibanding=50hz;antibanding-values=auto,50hz;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;best-capture=0;brightness=0;brightness-max=2;brightness-min=-2;burst-capture=0;burstshot-fps-values=(4,4);constant-growth-rate-zoom-supported=true;contrast=auto;drc=false;dual_mode=-1;dualrecording-hint=-1;dynamic-range-control=off;effect=none;effect-available-fps-values=(10000,15000);effect-values=none,mono,negative,sepia,posterize;effectrecording-hint=0;exposure-compensation=0;exposure-compensation-step=0.1;fast-fps-mode=-1;flash-mode=off;flash-mode-values=off,auto,on,torch;fnumber-value-denominator=10;fnumber-value-numerator=19;focal-length=3.70;focallength-35mm-value=28;focallength-value-denominator=100;focallength-value-numerator=370;focus-areas=(0,0,0,0,0);focus-distances=0.10,1.20,Infinity;focus-mode=auto;focus-mode-values=auto,macro,continuous-video,continuous-picture;hdr-mode=0;horizontal-view-angle=62.2;hue=0;hue-max=2;hue-min=-2;imageuniqueid-value=V13LLIA02AM V13LLKF01SA
[DEBUG] CameraConfiguration: ;intelligent-mode=-1;iso=auto;iso-values=auto,100,200,400,800;jpeg-quality=96;jpeg-thumbnail-height=384;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=512x384,512x288,384x384,320x240,0x0;jpeg-thumbnail-width=512;max-exposure-compensation=20;max-num-detected-faces-hw=16;max-num-detected-faces-sw=0;max-num-focus-areas=1;max-num-metering-areas=0;max-zoom=30;maxaperture-value-denominator=100;maxaperture-value-numerator=185;metering=center;metering-areas=;metering-values=matrix,center,spot;min-exposure-compensation=-20;odc=false;phase-af=off;phase-af-values=off;picture-format=jpeg;picture-format-values=jpeg;picture-size=4128x3096;picture-size-values=4128x3096,4128x2322,3264x2448,3264x1836,3088x3088,2160x2160,2048x1536,2048x1152,1920x1080,1440x1080,1280x720,960x720,640x480,320x240;preferred-preview-size-for-video=1280x720;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p;preview-fps-range=15000,30000;preview-fps-range-values=(15000,15000),(24000,24000),(15000,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30;preview-size=1280x720;preview-size-values=1280x720,1056x704,960x720,880x720,720x720,720x480,640x480,352x288,320x240,176x144;rotation=0;rt-hdr=off;rt-hdr-values=off;saturation=0;saturation-max=2;saturation-min=-2;scene-mode=auto;scene-mode-values=auto,action,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight;sharpness=0;sharpness-max=2;sharpness-min=-2;smooth-zoom-supported=false;vertical-view-angle=39.4;video-frame-format=nv21;video-size=1920x1080;video-size-values=1920x1080,1440x1080,1072x1072,1280x720,960x720,800x450,720x480,640x480,480x320,352x288,320x240,176x144;video-snapshot-supported=true;video-stabilization-supported=false;vrmode=-1;wdr=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,daylight,cloudy-daylight;zoom=0;zoom-ratios=100,104,109,114,120,125,131,138,144,151,158,166,174,182,190,200,209,219,229,240,251,263,276,289,303,317,332,348,364,381,400;zoom-supported=true
[INFO]  CameraConfiguration: Requesting flash mode value from among: [torch, on]
[INFO]  CameraConfiguration: Supported flash mode values: [off, auto, on, torch]
[INFO]  CameraConfiguration: Can set flash mode to: torch
[INFO]  CameraConfiguration: Setting flash mode to torch
[INFO]  CameraConfiguration: Requesting focus mode value from among: [auto]
[INFO]  CameraConfiguration: Supported focus mode values: [auto, macro, continuous-video, continuous-picture]
[INFO]  CameraConfiguration: Can set focus mode to: auto
[INFO]  CameraConfiguration: Focus mode already set to auto
[DEBUG] DecodeThread: Hints: {POSSIBLE_FORMATS=[CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E], NEED_RESULT_POINT_CALLBACK=com.google.zxing.client.android.ViewfinderResultPointCallback@893a531}
[DEBUG] AutoFocusManager: Current focus mode 'auto'; use auto focus? true
[TRACE] MediaPlayer: invoke 68
[INFO]  Choreographer: Skipped 62 frames!  The application may be doing too much work on its main thread.
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x1 surface={isValid=true -903028736} surfaceGenerationChanged=false
[DEBUG] SurfaceView: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x1 surface={Surface(name=null)/@0x5c4cdd8 isValid=true -900689920}
[DEBUG] CameraManager: Calculated framing rect: Rect(120, 240 - 600, 1040)
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: MSG_WINDOW_FOCUS_CHANGED 1
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -903028736}
[TRACE] InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@4cc5197 nm : com.graftongb.stockandgo ic=null
[INFO]  InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
[DEBUG] InputTransport: Input channel constructed: fd=79
[DEBUG] InputTransport: Input channel destroyed: fd=77
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: mHardwareRenderer.destroy()#1
[DEBUG] D/ViewRootImpl@9bf6ba0[TiActivity]: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: mHardwareRenderer.destroy()#1
[DEBUG] D/ViewRootImpl@7d5d3f1[StockandgoActivity]: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
[INFO]  APSAnalyticsRunnable: Analytics Started
[INFO]  I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO]  I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
[INFO]  art: Do partial code cache collection, code=62KB, data=57KB
[INFO]  art: After code cache collection, code=55KB, data=53KB
[INFO]  art: Increasing code cache capacity to 256KB
[INFO]  APSAnalyticsRunnable: Analytics service flush complete
[INFO]  APSAnalyticsRunnable: Stopping Service
[INFO]  I/InputDispatcher( 4047): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: ViewPostImeInputStage processPointer 0
[INFO]  I/InputDispatcher( 4047): Delivering touch to : action: 0x1, toolType: 1
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: ViewPostImeInputStage processPointer 1
[INFO]  I/InputDispatcher( 4047): Delivering touch to : action: 0x0, toolType: 1
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: ViewPostImeInputStage processPointer 0
[INFO]  I/InputDispatcher( 4047): Delivering touch to : action: 0x1, toolType: 1
[DEBUG] D/ViewRootImpl@2f2cd4a[CaptureActivity]: ViewPostImeInputStage processPointer 1
[TRACE] V/MediaPlayer-JNI: release
[TRACE] MediaPlayer: setListener
[TRACE] MediaPlayer: disconnect
[TRACE] MediaPlayer: destructor
[TRACE] MediaPlayer: disconnect
[INFO]  Choreographer: Skipped 57 frames!  The application may be doing too much work on its main thread.
[DEBUG] AndroidRuntime: Shutting down VM
[INFO]  art: Starting a blocking GC HeapTrim

**Comment by olli3** [comment]
update again (sorry)

if i remove the overlay it doesnt crash, and works alot better, however then the only cancel i have is back btn.

hope this helps

**Comment by olli3** [comment]
[INFO]  APSAnalyticsRunnable: Analytics Started
[INFO]  APSAnalyticsRunnable: Analytics service flush complete
[INFO]  APSAnalyticsRunnable: Stopping Service
[DEBUG] DecodeHandler: Found barcode in 32 ms
[DEBUG] CaptureActivityHandler: Got return scan result message
[TRACE] MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
[TRACE] MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
[WARN]  ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@fd0da59
[DEBUG] AndroidRuntime: Shutting down VM

**Comment by m1ga** [comment]
With the overlay is good to know! 
Sadly the log doesn't really show any significant crash/error besides some frame dropping (most of the time this is because of animations or heavy work in the background).

Any special things in the overlay? Big images, input fields?

**Comment by olli3** [comment]
so heres what i have so far

1. if i remove overlay the crash stops however i cannot cancel the process other than back button - scan success only fires on back btn press so kinda useless

2. if i remove everything from overlay and add it it still crashes - even when i click back (cancel btn and rotate camera btn)

[WARN]  ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f6c2b79
[DEBUG] AndroidRuntime: Shutting down VM
[INFO]  libc: Requested dump for tid 22655 (Shutdown thread)

3.

**Comment by m1ga** [comment]
When I press cancel I'll see this error
```

[ERROR] TiApplication: (main) [2807,45060] Sending event: exception on thread: main msg:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miga.qr/com.google.zxing.client.android.CaptureActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.; Titanium 7.2.0,2018/06/07 05:21,undefined
[ERROR] TiApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miga.qr/com.google.zxing.client.android.CaptureActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[ERROR] TiApplication:  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2725)
[ERROR] TiApplication:  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2786)
[ERROR] TiApplication:  at android.app.ActivityThread.-wrap12(ActivityThread.java)
[ERROR] TiApplication:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1501)
[ERROR] TiApplication:  at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] TiApplication:  at android.os.Looper.loop(Looper.java:173)
[ERROR] TiApplication:  at android.app.ActivityThread.main(ActivityThread.java:6459)
[ERROR] TiApplication:  at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
[ERROR] TiApplication:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
[ERROR] TiApplication: Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[ERROR] TiApplication:  at android.view.ViewGroup.addViewInner(ViewGroup.java:4466)
[ERROR] TiApplication:  at android.view.ViewGroup.addView(ViewGroup.java:4307)
[ERROR] TiApplication:  at android.view.ViewGroup.addView(ViewGroup.java:4247)
[ERROR] TiApplication:  at android.view.ViewGroup.addView(ViewGroup.java:4220)
[ERROR] TiApplication:  at com.google.zxing.client.android.CaptureActivity.onCreate(CaptureActivity.java:179)
[ERROR] TiApplication:  at android.app.Activity.performCreate(Activity.java:6673)
[ERROR] TiApplication:  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
[ERROR] TiApplication:  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
[ERROR] TiApplication:  ... 9 more

```

that would have helped :-) I'll check it now

**Comment by olli3** [comment]
sorry , i never saw this error ! but maybe it will help

**Comment by m1ga** [comment]
Sometimes it can be easy :smile: 
https://github.com/appcelerator-modules/ti.barcode/blob/master/ios/example/app.js#L102
add a `return`  below this line and it should work.
The module was opening the camera twice

**Comment by m1ga** [comment]
Bug was in `isiOS`: https://github.com/appcelerator-modules/ti.barcode/pull/89

**Comment by olli3** [comment]
great thanks so much for quick fix, i guess i just download the new version ?

**Comment by m1ga** [comment]
it is just a bug in the example, so if you implement it in your app you don't set isiOS to true on Android.

**Comment by olli3** [comment]
of course, thanks once again, great support  and great work.
